// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// apgr
arma::vec apgr(arma::mat A, arma::vec b, double lambda, double gamma, double t, double alpha, double beta, int max_iteration, double eps, int proximal, int method, int step);
RcppExport SEXP _apgr_apgr(SEXP ASEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP tSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP max_iterationSEXP, SEXP epsSEXP, SEXP proximalSEXP, SEXP methodSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type proximal(proximalSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(apgr(A, b, lambda, gamma, t, alpha, beta, max_iteration, eps, proximal, method, step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_apgr_apgr", (DL_FUNC) &_apgr_apgr, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_apgr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
