# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apgr <- function(A, b, lambda, gamma = 0, t = 0.0055, alpha = 1.01, beta = 0.5, max_iteration = 2000L, eps = 1e-6, proximal = 2L, method = 1L, step = 1L) {
    .Call(`_apgr_apgr`, A, b, lambda, gamma, t, alpha, beta, max_iteration, eps, proximal, method, step)
}

